# Generated by Django 5.2.7 on 2025-10-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_no",
            field=models.IntegerField(),
        ),
    ]
