# Generated by Django 5.2.7 on 2025-11-13 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_profile_phone_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("emp_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("join_date", models.DateField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic", models.DecimalField(decimal_places=2, max_digits=10)),
                ("hra", models.DecimalField(decimal_places=2, max_digits=10)),
                ("da", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax", models.DecimalField(decimal_places=2, max_digits=10)),
                ("month", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salaries",
                        to="myapp.employee",
                    ),
                ),
            ],
        ),
    ]
